[package]
name = "fse_dump"
description = "Dumps the fseventsd entries from a mac"

version = "0.3.1"
edition = "2018"

authors = ["Adam Lesperance <lespea@gmail.com>"]
categories = ["parsing", "command-line-utilities"]
keywords = ["mac", "fseventsd", "security", "forensics"]

license = "MIT OR Apache-2.0"
readme = "README.md"

homepage = "https://github.com/lespea/fse_dump"
repository = "https://github.com/lespea/fse_dump"

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "lespea/fse_dump" }

[dependencies]
bus = "2"
byteorder = "1"
clap = "2"
crossbeam = "0"
crossbeam-channel = "0"
csv = "1"
env_logger = "0"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
hashbrown = "0"
lazy_static = "1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
parking_lot = "0"
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
structopt = "0"
walkdir = "2"

# Use crc32fast -- change committed but not pushed to crates yet
[patch.crates-io]
miniz_oxide = { git = 'https://github.com/Frommi/miniz_oxide', rev = 'e8d2a584c57b60594707903adeef72ea6659bda9' }

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
incremental = false
lto = true

