[package]
name = "fsdump"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
csv = "1"
enum-display-derive = "0.1"
flate2 = "1"
serde = "1"
serde_derive = "1"

[profile.release]
lto = true
codegen-units = 1