[package]
name = "fse_dump"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
#edition = "2018"

[dependencies]
bitflags = "1"
byteorder = "1"
csv = "1"
enum-display-derive = "0.1"
flate2 = "1"
fnv = "1"
lazy_static = "1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
simple_logger = "1"

[dev-dependencies]
env_logger = "0"

[profile.release]
lto = true
codegen-units = 1
