[package]
name = "fse_dump"
description = "dump the fs events files on macs"
version = "0.1.0"
authors = ["Adam Lesperance <lespea@gmail.com>"]
#edition = "2018"

[dependencies]
byteorder = "1"
clap = "2"
crossbeam = "0"
csv = "1"
flate2 = "1"
fnv = "1"
lazy_static = "1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
num_cpus = "1"
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
simple_logger = "1"
structopt = "0"

[dev-dependencies]
env_logger = "0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
