[package]
name = "fse_dump"
description = "Dumps the fseventsd entries from a mac"

version = "0.3.0"

authors = ["Adam Lesperance <lespea@gmail.com>"]
categories = ["parsing", "command-line-utilities"]
keywords = ["mac", "fseventsd", "security", "forensics"]

license = "Apache-2.0"
readme = "README.md"

homepage = "https://github.com/lespea/fse_dump"
repository = "https://github.com/lespea/fse_dump"

[dependencies]
byteorder = "1"
clap = "2"
crossbeam = "0"
crossbeam-channel = "0"
csv = "1"
flate2 = "1"
fnv = "1"
lazy_static = "1"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
env_logger = "0"
structopt = "0"
walkdir = "2"

[profile.release]
codegen-units = 1
lto = true
